#!/bin/bash

env=common

if [[ `hostname -s` == *foreman* ]]		; then echo puppetmaster	; exit 0 ;fi
if [[ `hostname -s` == *dns* ]]			; then echo dns			; exit 0 ;fi
if [[ `hostname -s` == *kube-master* ]]		; then echo kube-master		; exit 0 ;fi
if [[ `hostname -s` == *kube-worker* ]]		; then echo kube-worker		; exit 0 ;fi
